version: '3.8'

services:
  dev:
    container_name: document_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npm rebuild esbuild && npm start"

  prod:
    container_name: document_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - resume:/usr/share/nginx/html
    ports:
      - 3001:80

volumes:
  resume:
