# first stage
FROM node:18-alpine3.17 as build

WORKDIR /app

COPY package.json .

COPY yarn.lock .

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

# 2nd stage
FROM nginx:1.23.3-alpine-slim

COPY --from=build /app/dist /usr/share/nginx/html

COPY .nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

